lang: en
title: FLOW Lab @ Uni. Gothenburg
tagline: FLOW-Lab
email: bastien.queste@gu.se
description: >- # this means to ignore newlines until "baseurl:"
  Fluxes in Low Oxygen Waters Research Lab at the University of Gothenburg, Sweden.
#baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "http://www.flow-lab.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DrQueste
github_username:  bastienqueste

# Build settings with GitHub Pages Gem

theme: bulma-clean-theme
force_theme: light
theme_color: '#024C8B'

plugins:
  - jekyll-feed

# Configure format of website
theme_color: '#074b89'
fixed_navbar: top

gems: ['jekyll/scholar']
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_data
  bibliography: scopus.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
